Repository Sibrox/kaizen, pull requests merged in 2023-10, with the labels that each got.

#90 fix: flutter analyze is ok
  lib/models/second_survey/question.dart
  lib/utilities/.gitkeep
  lib/utilities/bloc_test_custom.dart
  pubspec.lock
  pubspec.yaml
  test/main_survey/bloc_test.dart
Labels: hotfix

#78 fix: add Reward in the Shop
  lib/models/shop/bloc/shop_bloc.dart
  test/shop/bloc_test.dart
Labels: bug

#84 Feat/hugene/66 task manager bloc
  lib/models/task/task.g.dart
  lib/models/task_manager/bloc/task_manager_bloc.dart
  lib/models/task_manager/bloc/task_manager_event.dart
  lib/models/task_manager/task_manager.dart
  lib/models/task_manager/task_manager.g.dart
  test/task_manager/bloc_test.dart
Labels: coding

#85 feat(#71): create task widget
  lib/models/task/view/task_widget.dart
Labels: coding

#91 feat(#72): create task manager screen
  lib/screens/task_manager_screen.dart
Labels: coding
